# Generated by Django 5.2.17 on 2026-09-20 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactPageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=150)),
                ('phone_number', models.CharField(max_length=14)),
                ('linkedin_url', models.URLField(max_length=100)),
                ('instagram_url', models.URLField(max_length=100)),
                ('x_url', models.URLField(max_length=250)),
                ('facebook_url', models.URLField(max_length=250)),
                ('map_url', models.URLField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_page_data', to='cms.page')),
            ],
        ),
        migrations.CreateModel(
            name='AboutPageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt_message', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='about_page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_page_images', to='cms.page')),
            ],
        ),
        migrations.CreateModel(
            name='AboutPageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('subtitle', models.CharField(max_length=300)),
                ('first_description', models.CharField(max_length=300)),
                ('second_description', models.CharField(max_length=300)),
                ('third_description', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='about_page_data', to='cms.page')),
            ],
        ),
        migrations.CreateModel(
            name='HomePageSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('subtitle', models.CharField(max_length=300)),
                ('alt_message', models.CharField(max_length=300)),
                ('url', models.URLField(max_length=500)),
                ('order', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to='home_page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_page_sliders', to='cms.page')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('page', 'order'), name='unique_slider_order_per_page')],
            },
        ),
        migrations.CreateModel(
            name='HomePageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_type', models.CharField(choices=[('component_a', 'Component A'), ('component_b', 'Component B'), ('component_c', 'Component C')], default='component_a', max_length=20)),
                ('order', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='page_categories', to='blog.category')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_page_categories', to='cms.page')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('page', 'order'), name='unique_category_order_per_page')],
            },
        ),
    ]
