# Generated by Django 5.2.17 on 2026-10-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_test_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testservicemodel',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
